version: '3.8'

services:
  postgres-primary:
    image: bitnami/postgresql:14
    container_name: postgres-primary
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgrespw

      - POSTGRESQL_DATABASE=product_descriptions_db

      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
    volumes:
      - primary_data:/bitnami/postgresql
      - ./docker/initdb-master:/docker-entrypoint-initdb.d
    ports:
      - '5433:5432'

  postgres-replica:
    image: bitnami/postgresql:14
    container_name: postgres-replica
    depends_on:
      - postgres-primary
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgrespw

      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass

      - POSTGRESQL_MASTER_HOST=postgres-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - replica_data:/bitnami/postgresql
    ports:
      - '5434:5432'

volumes:
  primary_data:
    name: pg_primary_data
  replica_data:
    name: pg_replica_data
